# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4983b9c592b702cc0e4c1cdf095012db87a0368c7bec726e73343f2e3a3a2c7f92e371745e1c3e4964098f937f2e915b8f7c9b46c54ca586fb585dc74fbda37f

test:
  secret_key_base: 5533f11612b3b8217cfe4207348ee5293400c03f62082d6eaecaffca0e1106b8a69547e44fe1cd83545e5c6038cbe58c94f91059c151ec373d55cbfe375026b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
